package dev.gdx.markup.preview;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;

/**
 * Distribution launcher script tests. The macOS-only {@code -XstartOnFirstThread} option
 * (required before the classpath/main for any JVM that initializes GLFW) must be selected by
 * the generated Unix launcher AT RUNTIME on Darwin — a distribution built on Linux is
 * cross-platform and can be run on macOS — and must never appear in the Windows launcher
 * (the flag is a macOS-only HotSpot option). The scripts are generated by
 * {@code startScripts} before the test task runs and their paths arrive via system
 * properties.
 */
final class PreviewStartScriptTest {
    @Test
    void unixLauncherSelectsXstartOnFirstThreadAtRuntimeOnDarwin() throws Exception {
        String script = Files.readString(Path.of(System.getProperty("preview.unixScript")));
        assertTrue(script.contains("DEFAULT_JVM_OPTS"),
                "the Unix launcher defines DEFAULT_JVM_OPTS");
        // The unconditional default options must NOT bake the flag at build time.
        assertFalse(script.lines().filter(line -> line.startsWith("DEFAULT_JVM_OPTS="))
                        .anyMatch(line -> line.contains("-XstartOnFirstThread")),
                "the flag must not be baked into DEFAULT_JVM_OPTS at build time");
        // The flag is appended only when the script detected Darwin at runtime.
        assertTrue(script.contains("if [ \"$darwin\" = \"true\" ]; then"),
                "the flag must be selected at runtime via the script's darwin detection");
        assertTrue(script.contains("DEFAULT_JVM_OPTS=\"$DEFAULT_JVM_OPTS -XstartOnFirstThread\""),
                "the Darwin branch must append -XstartOnFirstThread to the JVM options");
    }

    @Test
    void windowsLauncherNeverCarriesTheMacOnlyFlag() throws Exception {
        String bat = Files.readString(Path.of(System.getProperty("preview.windowsScript")));
        assertFalse(bat.contains("XstartOnFirstThread"),
                "-XstartOnFirstThread is a macOS-only HotSpot option and must never appear "
                        + "in the Windows launcher");
    }
}
